# Generated by Django 3.2.10 on 2022-01-06 01:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='places',
        ),
    ]
